### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Jerrymarck** [pritom007/Network-Traffic-Classification#1]
Hello！
Can you share the dataset about this project?

Thanks!

**Comment by pritom007** [comment]
Hi,
We currently submitted a paper regarding this project. Temporarily we can't share the dataset. Ping me in a month, hopefully, by then we'll be able to open source it.

**Comment by qianwang102** [comment]
> 
> 
> Hi,
> We currently submitted a paper regarding this project. Temporarily we can't share the dataset. Ping me in a month, hopefully, by then we'll be able to open source it.

hello! Have you got your article? Can you share your article and the dataset?

**Comment by pritom007** [comment]
I am planning to open source my dataset. I will soon post the update.

**Comment by pritom007** [comment]
> Hello！
> Can you share the dataset about this project?
> 
> Thanks!

https://github.com/pritom007/Network-Traffic-Classification/blob/master/network_traffic.csv

**Comment by pritom007** [comment]
This is the raw data. You can process it according to your own need.

**Comment by pritom007** [comment]
> > Hello！
> > Can you share the dataset about this project?
> > Thanks!
> 
> https://github.com/pritom007/Network-Traffic-Classification/blob/master/network_traffic.csv

This is the raw data. You can process it according to your own need.
