### ISSUE TITLE
from dictionary import name_convert   THIS LINE GIVING ME ERROR 

### ISSUE THREAD

**Issue by salmanke** [pritom007/Network-Traffic-Classification#4]
![Screenshot (97)](https://user-images.githubusercontent.com/55252719/117919476-b1dc9400-b30a-11eb-94c8-0580b4222e6f.png)

**Comment by pritom007** [comment]
added two more files check that out. Just import the `name_convert` funtion from dictionary.py. Also added the `test.txt` file. It should run fine.
BTW this is a very old version of the project. I will upload a newer version of the code soon.
