### ISSUE TITLE
index out of bound problem...?

### ISSUE THREAD

**Issue by salmanke** [pritom007/Network-Traffic-Classification#5]
![Screenshot (111)](https://user-images.githubusercontent.com/55252719/118079688-3fd18100-b3d6-11eb-8b91-58902ef36ee6.png)

**Comment by salmanke** [comment]
![Screenshot (112)](https://user-images.githubusercontent.com/55252719/118082512-efa8ed80-b3da-11eb-9b19-089254993d6f.png)

**Comment by pritom007** [comment]
You can just comment that line. It's for debugging purposes. 
BTW i suggest you to write your own prediction function that will be a better approch.
